# Generated by Django 4.0.4 on 2022-04-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='categora',
            new_name='categoria',
        ),
    ]
